# Windows x64 cross-compilation from macOS with Clang and xwin's MSVC SDK.
# Pass WAVE_WINDOWS_SDK_ROOT, WAVE_CLANG_CL and WAVE_LLD_LINK when configuring.
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_TRY_COMPILE_CONFIGURATION Release)
if(NOT WAVE_WINDOWS_SDK_ROOT OR NOT WAVE_CLANG_CL OR NOT WAVE_LLD_LINK)
    message(FATAL_ERROR "Set WAVE_WINDOWS_SDK_ROOT, WAVE_CLANG_CL and WAVE_LLD_LINK")
endif()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    WAVE_WINDOWS_SDK_ROOT WAVE_CLANG_CL WAVE_LLD_LINK)
set(CMAKE_C_COMPILER "${WAVE_CLANG_CL}")
set(CMAKE_CXX_COMPILER "${WAVE_CLANG_CL}")
set(CMAKE_C_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc)
get_filename_component(WAVE_CLANG_BIN "${WAVE_CLANG_CL}" DIRECTORY)
set(CMAKE_RC_COMPILER "${WAVE_CLANG_BIN}/llvm-rc")
set(CMAKE_MT "${WAVE_CLANG_BIN}/llvm-mt")
set(CMAKE_LINKER "${WAVE_LLD_LINK}")
set(CMAKE_AR "${WAVE_CLANG_BIN}/llvm-lib")
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
set(WAVE_WINDOWS_INCLUDES "")
set(WAVE_WINDOWS_RC_INCLUDES "")
foreach(directory crt/include sdk/include/ucrt sdk/include/shared sdk/include/um sdk/include/winrt)
    string(APPEND WAVE_WINDOWS_INCLUDES " /imsvc\"${WAVE_WINDOWS_SDK_ROOT}/${directory}\"")
    string(APPEND WAVE_WINDOWS_RC_INCLUDES " -I\"${WAVE_WINDOWS_SDK_ROOT}/${directory}\"")
endforeach()
set(CMAKE_C_FLAGS_INIT "${WAVE_WINDOWS_INCLUDES}")
set(CMAKE_CXX_FLAGS_INIT "${WAVE_WINDOWS_INCLUDES}")
set(CMAKE_RC_FLAGS_INIT "${WAVE_WINDOWS_RC_INCLUDES}")
set(WAVE_WINDOWS_LIBRARIES "")
foreach(directory crt/lib/x86_64 sdk/lib/um/x86_64 sdk/lib/ucrt/x86_64)
    string(APPEND WAVE_WINDOWS_LIBRARIES " /libpath:\"${WAVE_WINDOWS_SDK_ROOT}/${directory}\"")
endforeach()
# CMake's MSVC linker wrapper asks lld to embed manifests (EXE resource 1,
# DLL resource 2). Preserve JUCE's Common Controls v6 dependency: disabling
# manifests makes Windows load comctl32 v5, which lacks TaskDialogIndirect.
set(CMAKE_EXE_LINKER_FLAGS_INIT "${WAVE_WINDOWS_LIBRARIES}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${WAVE_WINDOWS_LIBRARIES}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${WAVE_WINDOWS_LIBRARIES}")
set(CMAKE_FIND_ROOT_PATH "${WAVE_WINDOWS_SDK_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
